<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\LMSupply.Core\LMSupply.Core.csproj" />
    <ProjectReference Include="..\..\src\LMSupply.Generator\LMSupply.Generator.csproj" />
  </ItemGroup>
</Project>
